project_id = "afhdmpuwczqnbbxrgytt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.email-generator]
verify_jwt = true

[functions.social-media-automation]
verify_jwt = true

[functions.workflow-automation]
verify_jwt = false

[functions.nexus-backend-connector]
verify_jwt = false
